language: perl
perl:
  - 5.12
  - 5.14
  - 5.16
before_install:
  cpanm -n Devel::Cover::Report::Coveralls
script:
  perl Build.PL && ./Build build && ./Build test && HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,inc" PERL5LIB="lib" prove t/*.t && cover -report coveralls
